# Generated by Django 5.2.8 on 2025-11-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10, unique=True)),
                ('level', models.IntegerField()),
                ('max_length', models.FloatField()),
                ('max_height', models.FloatField()),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('length', models.FloatField()),
                ('height', models.FloatField()),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('assigned_spot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking_app.parkingspot')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_subscription', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('cb', 'Carte bancaire')], max_length=20)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking_app.vehicle')),
            ],
        ),
    ]
