# Generated by Django 5.2.8 on 2025-12-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='amount_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
