# Generated by Django 5.2.8 on 2025-12-22 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0002_ticket_amount_paid_ticket_exit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='subscription_type',
            field=models.CharField(choices=[('NONE', 'Client occasionnel'), ('STANDARD', 'Abonné'), ('GUARANTEED', 'Pack garanti')], default='NONE', max_length=20),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('STANDARD', 'Abonné Standard - 50€/mois'), ('GUARANTEED', 'Pack Garanti - 100€/mois')], max_length=20)),
                ('prix_mensuel', models.FloatField()),
                ('duree_mois', models.IntegerField(default=12)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='parking_app.abonne')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='parking_app.subscription'),
        ),
    ]
